#include<stdio.h>
int main(void)
{
*leddir=0x03;
*led=0x00;
enable_IRQ();		// call function to enable IRQ
*vic1intselect=0x00; 	// selected for IRQ interrupt
*vic1intenable=0x10;	// VIC Int source number 4 for Timer counter under flow
*vic1vectaddr0=(unsigned)timer_ISR; // load the starting address of ISR
*vic1vectctrl0=0x24;		// Enables vector interrupt and source number 4 
*timer1load=0x07d0;		// load starting value of timer 
*timer1control=0xc0;		// periodic timer enabled for 2 KHz clock
while(1);				// wait in infinite loop for interrupt 
}
__inline void enable_IRQ(void)
{
int temp;
	__asm
		{
		MRS 	temp,CPSR
		BIC	temp,temp,#0x80
		MSR	CPSR_c,temp;
		}
}
void timer_ISR(void)
{
*led=~*led;		// toggle the Led on periodic basis 
*timer1clear=0x00;	// any value clears interrupt generated by timer
}
